# Generated by Django 4.0.3 on 2022-03-26 10:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True, validators=[accounts.models.validate_date]),
        ),
    ]
